---
title: "Ejercicios para desarrollar en R"
author: "JRojas, MRamirez, LRomero"
date: "6/24/2020"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

A continuación se presentan una serie de ejercicios que permitiran interiorizar el manejo de R y su aplicación en operaciones algebraicas. En documento contiene la solución de 25 ejericios que hacen enfasis en el manejo de Algebra Lineal con R.

### Ejercicio 1

Hola























###################### MIGUEL





























######################### LUCHO
# Punto 25. 
```{r}
require(MASS)
A25 <- matrix(c(1,3,2,2,6,4), ncol=3, byrow=TRUE)
A25

G251 <- matrix(c(1,0,0,0,0,0), ncol=2, byrow=TRUE)
G251

G252 <-matrix(c(-42,-1,5,3,2,2), ncol=2, byrow=TRUE)
G252

#Para saber si corresponden a inversas generalizadas, debe cumplirse la propiedad AA-A= A, siendo A- cualquiera de las matrices inversas propuestas.

A25%*%G251%*%A25 == A25
A25%*%G252%*%A25 == A25

#Dado que se cumple la propiedad, podemos afirmar que las matrices G251 y G252 son inversas generalizadas de A25 
```

#Punto 24

```{r}
# Recuerda: EL rango de una matriz corresponde al número de filas o columnas linealmente independientes
A24 <- matrix(c(6,4,10,16,1,2,3,4,3,6,9,12,8,-1,7,15), ncol= 4)
A24
rA24 <- qr(A24) 
rA24$rank # Rango 2

B24 <- matrix(c(1,2,5,2,3,8,3,4,11,4,5,14,5,1,7), ncol= 5)
B24
rB24 <- qr(B24) 
rB24$rank # Rango 2
```

#Punto 23
```{r}
A23 <- matrix(c(1,2,3,1,-3,-2,-1,4,3), ncol= 3)
A23

B23 <- matrix(c(-1,6,5,-1,12,10,-1,6,5), ncol= 3)
B23

A23B23 <- A23%*%B23
A23B23
rA23B23 <- qr(A23B23) 
rA23B23$rank # Rango 1

B23A23 <- B23%*%A23
B23A23
rB23A23 <- qr(B23A23)
rB23A23$rank # Rango 2

# RESPUESTA: efectivamente, los rangos son diferentes, demostrando nuevamente que la multiplicación
# de matrices no es conmutativa.
```

#Punto 22

```{r}
A22 <- matrix(c(2,1,3,1,1,2,3,-1,3,-1,2,4,1,4,5,-3), ncol= 4)
A22

#A22inv <- solve(A22)

# RESPUESTA, la matriz es singular, por lo que no es invertible

A22vv <- eigen(A22)
A22vv
rA22 <- qr(A22)
rA22$rank

# RESPUESTA, dado que la matriz cuadrada tiene dos valores propios diferentes a 0, entonces el rango
# de la matriz es de 2. Esto se comprueba con el comando qr() y el paquete matlib
```

#Punto 21

```{r}
A21 <- matrix(c(1,2,1,-1,-1,0,1,0,1), ncol= 3)
A21

# Pruebe que A^2 = A^-1

A21A21 <- A21%*%A21
A21A21

A21inv <- solve(A21)
A21inv

A21A21 == A21inv

# El cuadrado de una matriz no es equivalente a su inversa
```

#Punto 20

```{r}
A20 <- matrix(c(-1,4,4,2,-3,-4,-2,4,5), ncol= 3)
A20

A20inv <- solve(A20)
A20inv

# En este caso se cumple con la igualdad
```

#Punto 19

```{r}
A19 <- matrix(c(1,2,3,2,4,1,1,6,2), ncol= 3)
A19

B19 <- matrix(c(-1,2,3,2,-1,4,-3,4,1), ncol= 3)
B19

A19B19 <- A19%*%B19
A19B19

A19B19det <- det(A19B19)
A19B19det #80

A19det <- det(A19)
A19det

B19det <- det(B19)
B19det

A19det*B19det#80

#RESPUESTA: se cumple la relación y en ambos casos el resultado es 80
```

#Punto 18

```{r}
A18 <- matrix(c(12,8,8,12,5,6,3,4,-3,4,-1,2,2,6,-1,4), ncol= 4)
A18

A18det <- det(A18)
A18det # 616
# Efectivamente la respuesta es 616
```

#Punto 17

```{r}

# Una matriz es idempotente cuando es igual a su cuadrado, es decir A*A = A
A17 <- matrix(c(2,-1,1,-2,3,-2,-4,4,-3), ncol= 3)
A17

A17A17 <- A17%*%A17
A17A17

A17 == A17A17

#RESPUESTA: Efectivamente la matriz A17 es idempotente
```

#Punto 16

```{r}
A16 <- matrix(c(1,2,-3,-2,3,1,3,-1,2), ncol= 3)
A16

B16 <- matrix(c(1,0,1,0,1,2,2,2,0), ncol= 3)
B16

A16B16 <- A16%*%B16
A16B16

B16A16 <- B16%*%A16
B16A16

A16B16 == B16A16
# RESPUESTA: efectivamente los resultados cambian, la multiplicación de matrices no es conmutativa
```



































